In [1]:
# -*- coding: utf-8 -*-

In [1]:
# add path
import sys
my_path = r'D:\Documents\etudes\epfl\MA1\cours\MachineLearning\Project1'
sys.path.insert(0,my_path + r'\code\COMMON')

# import external modules
import numpy as np
import matplotlib.pyplot as plt

# import internal modules
from proj1_helpers import load_csv_data 
from implementations import *

In [3]:
y = np.array([4,8,10])
X = np.array([[1,2],[1,4],[1,5]])

w_initials = np.zeros(X.shape[1])
max_iters = 15
gamma = 0.1

least_squares_SGD(y, X, w_initials, max_iters, gamma)

0
[8]
[[1 4]]

1
[4]
[[1 2]]

2
[4]
[[1 2]]

3
[10]
[[1 5]]

4
[10]
[[1 5]]

5
[4]
[[1 2]]

6
[4]
[[1 2]]

7
[8]
[[1 4]]

8
[8]
[[1 4]]

9
[4]
[[1 2]]

10
[4]
[[1 2]]

11
[4]
[[1 2]]

12
[8]
[[1 4]]

13
[4]
[[1 2]]

14
[4]
[[1 2]]

Gradient Descent(14/14): loss MSE=0.0002303025195237544, w0=0.06987812469999975, w1=1.9704263654000003


([array([ 0.,  0.]),
  array([ 0.8,  3.2]),
  array([ 0.48,  2.56]),
  array([ 0.32,  2.24]),
  array([ 0.168,  1.48 ]),
  array([ 0.4112,  2.696 ]),
  array([ 0.23088,  2.33536]),
  array([ 0.14072,  2.15504]),
  array([ 0.064632,  1.850688]),
  array([ 0.1178936,  2.0637344]),
  array([ 0.09335736,  2.01466192]),
  array([ 0.08108924,  1.99012568]),
  array([ 0.07495518,  1.97785756]),
  array([ 0.07631664,  1.98330339]),
  array([ 0.0720243 ,  1.97471871]),
  array([ 0.06987812,  1.97042637])],
 [32.0,
  5.120000000000001,
  1.2799999999999994,
  1.155200000000002,
  2.9573120000000053,
  1.6257651200000023,
  0.40644128000000096,
  0.28946918720000153,
  0.14183990172800093,
  0.030101353666880076,
  0.0075253384167200737,
  0.0018813346041800184,
  9.2678394288194538e-05,
  0.00092121007809501765,
  0.00023030251952375441])

In [4]:
for k in np.arange(10):
    
    batches = batch_iter(y, X, 1, num_batches=1, shuffle=True)

    for samples in batches:

        print(samples[0])
        print(samples[1])
        print()

[10]
[[1 5]]

[10]
[[1 5]]

[8]
[[1 4]]

[8]
[[1 4]]

[4]
[[1 2]]

[4]
[[1 2]]

[4]
[[1 2]]

[8]
[[1 4]]

[10]
[[1 5]]

[8]
[[1 4]]



# Load Data

In [38]:
y, input_data, ids = load_csv_data(my_path + r'\data\train.csv', sub_sample=False)

In [39]:
np.shape(input_data)

(250000, 30)

# Process the Counting -999

In [40]:
nine_count = []

for i in range(0, np.shape(input_data)[1],1):
    nine_count.append(np.shape(np.where((input_data.T)[i]==-999))[1])

print(nine_count)

[38114, 0, 0, 0, 177457, 177457, 177457, 0, 0, 0, 0, 0, 177457, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 99913, 99913, 99913, 177457, 177457, 177457, 0]


# Removal of the -999 lines

In [41]:
print(np.where((input_data.T)[:]==-999))

X_no_999 = np.delete(input_data, np.where((input_data.T)[:]==-999), axis=0)
y_no_999 = np.delete(y, np.where((input_data.T)[:]==-999), axis=0)

np.shape(X_no_999)
np.shape(y_no_999)

(array([ 0,  0,  0, ..., 28, 28, 28], dtype=int64), array([     2,     10,     14, ..., 249997, 249998, 249999], dtype=int64))


(68109,)

# Plotting distributions vs. log-distributions

Problems: 
-negative numbers cannot be logged, for now i did abs but it's not fair.
-zero can't be logged, i added one.

In [ ]:
for i in range(0, np.shape(input_data)[1],1):
    plt.subplot(121)
    plt.hist([(in_data.T)[i]], bins=400, log=False,color='r', alpha=0.5,histtype='stepfilled')
    plt.subplot(122)
    plt.hist([np.log(1+np.abs(in_data.T)[i])], bins=400, log=False,color='b', alpha=0.5,histtype='stepfilled')
    plt.show()

# Split input data

In [42]:
# primitive data
x_pri = X_no_999[:,:13]

# derived features from primitive data
x_der = X_no_999[:,13:]

print(X_no_999.shape)
print(x_pri.shape)
print(x_der.shape)
print(y_no_999.shape)

(68109, 30)
(68109, 13)
(68109, 17)
(68109,)


# Least Square GD

In [43]:
# PRI and DER 
initial_w = np.zeros(X_no_999.shape[1])
max_iters = 10
gamma = 0.1
w_ls, loss_ls = least_squares_GD(y_no_999, y_no_999, initial_w, max_iters, gamma)

# DER
w_ls, loss_ls = least_squares_GD(yb, x_der, initial_w, max_iters, gamma)

Gradient Descent(9/9): loss MSE=9.030576889717227e+113, w0=-2.078515220740841e+52, w1=1.0457293247425486e+52


ValueError: shapes (68109,17) and (30,) not aligned: 17 (dim 1) != 30 (dim 0)

# Least Square SGD

In [ ]:
# params 
initial_w = np.zeros(input_data.shape)
max_iters = 10
gamma = 0.1

# PRI and DER
w_ls, loss_ls = least_squares_SGD(yb, in_data, initial_w, max_iters, gamma)

# DER
w_ls, loss_ls = least_squares_SGD(yb, x_der, initial_w, max_iters, gamma)