In [1]:
# -*- coding: utf-8 -*-

In [1]:
# add path
import sys
my_path = r'D:\Documents\etudes\epfl\MA1\cours\MachineLearning\Project1'
sys.path.insert(0,my_path + r'\code\COMMON')

# import external modules
import numpy as np
import matplotlib.pyplot as plt

# import internal modules
from proj1_helpers import load_csv_data 
from implementations import *

In [4]:
y = np.array([4,8,10])
X = np.array([[1,2],[1,4],[1,5]])

w_initials = np.zeros(X.shape[1])
max_iters = 15
gamma = 0.1

least_squares_SGD(y, X, w_initials, max_iters, gamma)

0
[4]
[[1 2]]

1
[4]
[[1 2]]

2
[8]
[[1 4]]

3
[8]
[[1 4]]

4
[10]
[[1 5]]

5
[8]
[[1 4]]

6
[8]
[[1 4]]

7
[8]
[[1 4]]

8
[4]
[[1 2]]

9
[8]
[[1 4]]

10
[4]
[[1 2]]

11
[10]
[[1 5]]

12
[10]
[[1 5]]

13
[4]
[[1 2]]

14
[4]
[[1 2]]

Gradient Descent(14/14): loss MSE=0.003576772265949291, w0=0.6438243224662001, w1=1.6992324960884


([array([ 0.,  0.]),
  array([ 0.4,  0.8]),
  array([ 0.6,  1.2]),
  array([ 0.86,  2.24]),
  array([ 0.678,  1.512]),
  array([ 0.8542,  2.393 ]),
  array([ 0.61158,  1.42252]),
  array([ 0.781414,  2.101856]),
  array([ 0.6625302,  1.6263208]),
  array([ 0.67101302,  1.64328644]),
  array([ 0.74659714,  1.94562293]),
  array([ 0.68281284,  1.81805433]),
  array([ 0.70550439,  1.93151209]),
  array([ 0.66919791,  1.74997967]),
  array([ 0.65228219,  1.71614822]),
  array([ 0.64382432,  1.6992325 ])],
 [8.0,
  2.0,
  3.379999999999999,
  1.6562000000000006,
  1.5523219999999978,
  2.9432232199999948,
  1.4421793777999998,
  0.70666789512200057,
  0.0035979117576200015,
  0.285647974925544,
  0.203421845048814,
  0.02574532565539003,
  0.0659080336777986,
  0.014307089063797164,
  0.003576772265949291])

In [4]:
for k in np.arange(10):
    
    batches = batch_iter(y, X, 1, num_batches=1, shuffle=True)

    for samples in batches:

        print(samples[0])
        print(samples[1])
        print()

[10]
[[1 5]]

[10]
[[1 5]]

[8]
[[1 4]]

[8]
[[1 4]]

[4]
[[1 2]]

[4]
[[1 2]]

[4]
[[1 2]]

[8]
[[1 4]]

[10]
[[1 5]]

[8]
[[1 4]]



# Load Data

In [38]:
y, input_data, ids = load_csv_data(my_path + r'\data\train.csv', sub_sample=False)

In [39]:
np.shape(input_data)

(250000, 30)

# Process the Counting -999

In [40]:
nine_count = []

for i in range(0, np.shape(input_data)[1],1):
    nine_count.append(np.shape(np.where((input_data.T)[i]==-999))[1])

print(nine_count)

[38114, 0, 0, 0, 177457, 177457, 177457, 0, 0, 0, 0, 0, 177457, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 99913, 99913, 99913, 177457, 177457, 177457, 0]


# Removal of the -999 lines

In [41]:
print(np.where((input_data.T)[:]==-999))

X_no_999 = np.delete(input_data, np.where((input_data.T)[:]==-999), axis=0)
y_no_999 = np.delete(y, np.where((input_data.T)[:]==-999), axis=0)

np.shape(X_no_999)
np.shape(y_no_999)

(array([ 0,  0,  0, ..., 28, 28, 28], dtype=int64), array([     2,     10,     14, ..., 249997, 249998, 249999], dtype=int64))


(68109,)

# Plotting distributions vs. log-distributions

Problems: 
-negative numbers cannot be logged, for now i did abs but it's not fair.
-zero can't be logged, i added one.

In [ ]:
for i in range(0, np.shape(input_data)[1],1):
    plt.subplot(121)
    plt.hist([(in_data.T)[i]], bins=400, log=False,color='r', alpha=0.5,histtype='stepfilled')
    plt.subplot(122)
    plt.hist([np.log(1+np.abs(in_data.T)[i])], bins=400, log=False,color='b', alpha=0.5,histtype='stepfilled')
    plt.show()

# Split input data

In [42]:
# primitive data
x_pri = X_no_999[:,:13]

# derived features from primitive data
x_der = X_no_999[:,13:]

print(X_no_999.shape)
print(x_pri.shape)
print(x_der.shape)
print(y_no_999.shape)

(68109, 30)
(68109, 13)
(68109, 17)
(68109,)


# Least Square GD

In [43]:
# PRI and DER 
initial_w = np.zeros(X_no_999.shape[1])
max_iters = 10
gamma = 0.1
w_ls, loss_ls = least_squares_GD(y_no_999, y_no_999, initial_w, max_iters, gamma)

# DER
w_ls, loss_ls = least_squares_GD(yb, x_der, initial_w, max_iters, gamma)

Gradient Descent(9/9): loss MSE=9.030576889717227e+113, w0=-2.078515220740841e+52, w1=1.0457293247425486e+52


ValueError: shapes (68109,17) and (30,) not aligned: 17 (dim 1) != 30 (dim 0)

# Least Square SGD

In [ ]:
# params 
initial_w = np.zeros(input_data.shape)
max_iters = 10
gamma = 0.1

# PRI and DER
w_ls, loss_ls = least_squares_SGD(yb, in_data, initial_w, max_iters, gamma)

# DER
w_ls, loss_ls = least_squares_SGD(yb, x_der, initial_w, max_iters, gamma)