In [1]:
# -*- coding: utf-8 -*-

In [2]:
# add path
import sys
my_path = r'D:\Documents\etudes\epfl\MA1\cours\MachineLearning\Project1'
sys.path.insert(0,my_path + r'\code\COMMON')

# import external modules
import numpy as np
import matplotlib.pyplot as plt

# import internal modules
from proj1_helpers import load_csv_data 
from implementations import *

In [11]:
y = np.array([4,8,10])
X = np.array([[1,2],[1,4],[1,5]])

w_initials = np.zeros(X.shape[1])
max_iters = 1000
gamma = 0.1

ws, losses = least_squares_SGD(y, X, w_initials, max_iters, gamma)
ws, losses = least_squares_GD(y, X, w_initials, max_iters, gamma)

Gradient Descent(999/999): loss MSE=3.347438309165019e-10, w0=6.69289572546865e-05, w1=1.9999877957911238
Gradient Descent(999/999): loss MSE=3.232840691642994e-11, w0=2.496486170319057e-05, w1=1.999993857420329


In [4]:
for k in np.arange(10):
    
    batches = batch_iter(y, X, 1, num_batches=1, shuffle=True)

    for samples in batches:

        print(samples[0])
        print(samples[1])
        print()

[10]
[[1 5]]

[10]
[[1 5]]

[8]
[[1 4]]

[8]
[[1 4]]

[4]
[[1 2]]

[4]
[[1 2]]

[4]
[[1 2]]

[8]
[[1 4]]

[10]
[[1 5]]

[8]
[[1 4]]



# Load Data

In [38]:
y, input_data, ids = load_csv_data(my_path + r'\data\train.csv', sub_sample=False)

In [39]:
np.shape(input_data)

(250000, 30)

# Process the Counting -999

In [40]:
nine_count = []

for i in range(0, np.shape(input_data)[1],1):
    nine_count.append(np.shape(np.where((input_data.T)[i]==-999))[1])

print(nine_count)

[38114, 0, 0, 0, 177457, 177457, 177457, 0, 0, 0, 0, 0, 177457, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 99913, 99913, 99913, 177457, 177457, 177457, 0]


# Removal of the -999 lines

In [41]:
print(np.where((input_data.T)[:]==-999))

X_no_999 = np.delete(input_data, np.where((input_data.T)[:]==-999), axis=0)
y_no_999 = np.delete(y, np.where((input_data.T)[:]==-999), axis=0)

np.shape(X_no_999)
np.shape(y_no_999)

(array([ 0,  0,  0, ..., 28, 28, 28], dtype=int64), array([     2,     10,     14, ..., 249997, 249998, 249999], dtype=int64))


(68109,)

# Plotting distributions vs. log-distributions

Problems: 
-negative numbers cannot be logged, for now i did abs but it's not fair.
-zero can't be logged, i added one.

In [ ]:
for i in range(0, np.shape(input_data)[1],1):
    plt.subplot(121)
    plt.hist([(in_data.T)[i]], bins=400, log=False,color='r', alpha=0.5,histtype='stepfilled')
    plt.subplot(122)
    plt.hist([np.log(1+np.abs(in_data.T)[i])], bins=400, log=False,color='b', alpha=0.5,histtype='stepfilled')
    plt.show()

# Split input data

In [42]:
# primitive data
x_pri = X_no_999[:,:13]

# derived features from primitive data
x_der = X_no_999[:,13:]

print(X_no_999.shape)
print(x_pri.shape)
print(x_der.shape)
print(y_no_999.shape)

(68109, 30)
(68109, 13)
(68109, 17)
(68109,)


# Least Square GD

In [43]:
# PRI and DER 
initial_w = np.zeros(X_no_999.shape[1])
max_iters = 10
gamma = 0.1
w_ls, loss_ls = least_squares_GD(y_no_999, y_no_999, initial_w, max_iters, gamma)

# DER
w_ls, loss_ls = least_squares_GD(yb, x_der, initial_w, max_iters, gamma)

Gradient Descent(9/9): loss MSE=9.030576889717227e+113, w0=-2.078515220740841e+52, w1=1.0457293247425486e+52


ValueError: shapes (68109,17) and (30,) not aligned: 17 (dim 1) != 30 (dim 0)

# Least Square SGD

In [ ]:
# params 
initial_w = np.zeros(input_data.shape)
max_iters = 10
gamma = 0.1

# PRI and DER
w_ls, loss_ls = least_squares_SGD(yb, in_data, initial_w, max_iters, gamma)

# DER
w_ls, loss_ls = least_squares_SGD(yb, x_der, initial_w, max_iters, gamma)