# LEAST SQUARES POLYNOMIAL IMPLEMENTATION

# Load data

In [92]:
import sys
my_path = r'C:\Users\utente\Documents\GitHub\Project1_ML'
sys.path.insert(0,my_path + r'\code\COMMON')

# import external modules
import numpy as np
import matplotlib.pyplot as plt

# import internal modules
from proj1_helpers import *
from implementations import *
from standard import standardize

In [44]:
yb, input_data, ids = load_csv_data(my_path + r'\data\train.csv', sub_sample=False)

print("Data loaded! Shape: ")
print(np.shape(input_data))

Data loaded! Shape: 
(250000, 30)


# Remove -999 or substitution with mean

In [45]:
X = input_data
nine_count=[]

for i in range(0, np.shape(input_data)[1],1):
    nine_count.append(np.shape(np.where((input_data.T)[i]==-999))[1])
    
print(nine_count)

[38114, 0, 0, 0, 177457, 177457, 177457, 0, 0, 0, 0, 0, 177457, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 99913, 99913, 99913, 177457, 177457, 177457, 0]


In [46]:
DELETE = 1;
MEAN_SUB = 0;

delete_method = DELETE

if delete_method:
    Y = yb
    for i in range(input_data.shape[1]):
        del_idx = np.where(X[:,i] == -999)
        X = np.delete(X, del_idx, 0)      
        Y = np.delete(Y, del_idx, 0)
    print("-999 Deleted! Shape:")
    
else:
    for i in range(input_data.shape[1]):
        X = np.delete(X, np.where(X[:,i] == -999), 0)

    means = np.mean(X, axis=0)

    for i in range(input_data.shape[1]):
        input_data[np.where(input_data[:,i]==-999),i] = means[i]
    X = input_data
    Y = yb
    
    print("-999 Substituted with the mean! Shape")
    
print(np.shape(X))

-999 Deleted! Shape:
(68114, 30)


In [48]:
nine_count=[]

for i in range(0, np.shape(X)[1],1):
    nine_count.append(np.shape(np.where((X.T)[i]==-999))[1])

print(nine_count)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


# Standardization

In [49]:
Xstd, mean_X, std_X = standardize(X)    
Xstd.shape

(68114, 30)

# Build_poly

In [50]:
def build_poly(x, degree):
    """polynomial basis functions for input data x, for j=0 up to j=degree."""
    
    X = np.vander((x[:,0]).T, degree+1, increasing=True)
    
    for i in range(1,np.shape(x)[1],1):
        feat = (x[:,i]).T
        X = np.concatenate((X, np.vander(feat, degree+1, increasing=True) ), axis=1)
    
    return X
    

Build_poly testing

In [51]:
A = np.array([[2, 3, 4], [5, 6, 7]])
b = np.array([[2,3]])

print(b)

build_poly(A, 3)


[[2 3]]


array([[  1,   2,   4,   8,   1,   3,   9,  27,   1,   4,  16,  64],
       [  1,   5,  25, 125,   1,   6,  36, 216,   1,   7,  49, 343]])

# Least Squares

In [52]:
w, loss = least_squares(Y, X)

In [53]:
w

array([ -5.02525476e-04,  -4.39262759e-03,  -2.63032799e-03,
         2.83231602e-03,  -2.58453648e-02,   5.44117177e-04,
        -1.14380173e-03,   2.97250499e-01,  -2.09316910e-03,
        -2.29452735e+00,  -1.75920265e-01,   1.15293534e-01,
         3.87186834e-01,   2.29846624e+00,  -3.69439017e-03,
        -1.23079369e-04,   2.30186971e+00,  -5.69629494e-03,
         1.97880259e-03,   1.18885088e-03,   3.22134579e-03,
        -1.02519616e-03,  -3.29758047e-01,  -4.23805741e-03,
         3.38420092e-03,   3.62244550e-03,  -1.32324259e-03,
         2.61260961e-03,  -1.82969838e-03,   2.29659038e+00])

In [54]:
loss

0.36925361647376992

In [71]:
y_model = np.sign(X.dot(w))

In [72]:
np.shape(y_model)

(68114,)

In [74]:
pos = 0
neg = 0
for i in range (len(Y)):
    if Y[i] == y_model[i]:
        pos += 1
    else:
        neg += 1
print(pos)
print(neg)

49305
18809


In [77]:
success_rate = pos/(pos+neg)
print(success_rate)

0.7238599994127493


# Load data for the test

In [79]:
nope, test_data, ids = load_csv_data(my_path + r'\data\test.csv', sub_sample=False)

print("Data loaded! Shape: ")
print(np.shape(test_data))

Data loaded! Shape: 
(568238, 30)


In [83]:
y_predictions = np.sign(test_data.dot(w))
np.shape(y_predictions)

(568238,)

In [89]:
y_predictions

array([-1., -1., -1., ..., -1., -1., -1.])

In [93]:
create_csv_submission(ids, y_predictions, "first_sub")